[package]
name = "snake-client-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = { version = "0.3.106" }
#snake-client = { path = "../client" }
snake-core = { path = "../game" }
wasm-bindgen = "0.2.129"
web-sys = { version = "0.3.106", features = [
  "console",
  "WebSocket",
  "MessageEvent",
  "ErrorEvent",
  "BinaryType",
  "CanvasRenderingContext2d",
  "Document",
  "Element",
  "HtmlCanvasElement",
  "Window",
  "KeyboardEvent",
] }
getrandom = { version = "0.4", features = ["wasm_js"] }
