[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[dependencies]
#console = "0.16.6"
crossterm = "0.29.0"
rand = "0.10.3"
colored = "3.1.1"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tracy-client = { version = "0.19.0", features = [
  "enable",
  "sampling",
  "system-tracing",
] }
